### ISSUE TITLE
Sidebar Problem Links Broken

### ISSUE THREAD

**Issue by truell20** [HMProgrammingClub/NYCSL2#18]
When you click on one, it just shows you the steiner problem.

**Comment by truell20** [comment]
ping @joshuagruenstein @FlyingGraysons

**Comment by joshuagruenstein** [comment]
Is the URL format for Problem pages not, for example, `http://192.241.178.181/?game=TS`?  Otherwise, I think the issue is on your end.

**Comment by truell20** [comment]
Hmm. Doesn't seem to be my end.
http://192.241.178.181:5000/problems
http://192.241.178.181:5000/problems/5779c0cf8bb6252e71cb0c0e

**Comment by truell20** [comment]
@FlyingGraysons ?

**Comment by hmwildermuth** [comment]
I know what the problem is

**Comment by hmwildermuth** [comment]
Will fix

**Comment by joshuagruenstein** [comment]
Wait no, I got it.

**Comment by truell20** [comment]
@joshuagruenstein @FlyingGraysons Is this still a problem?

**Comment by hmwildermuth** [comment]
No it has been fixed.
