### ISSUE TITLE
Continuous backup

### ISSUE THREAD

**Issue by joshuagruenstein** [HMProgrammingClub/NYCSL2#3]
Right now, we have no backups of our database and user's submissions. Backups should be done automatically periodically.

**Comment by hmwildermuth** [comment]
How periodically. I can do schedule in any interval.

**Comment by truell20** [comment]
This is easily done with hourly with rsync and another server. @FlyingGraysons What was your plan for doing them.

**Comment by hmwildermuth** [comment]
My plan was pretty much that. As I already asked, what interval do you backups done? Hourly? @truell20

**Comment by truell20** [comment]
Hourly

**Comment by truell20** [comment]
We should just open a 5 dollar a month server from DO with an big storage volume, since the thing is just acting as an SSD.

**Comment by truell20** [comment]
ping @joshuagruenstein

**Comment by hmwildermuth** [comment]
dw i got it

**Comment by hmwildermuth** [comment]
Finished. I will dm you the server details.

**Comment by truell20** [comment]
@FlyingGraysons Are you just backing up the whole NYCSL2 folder? Or all of storage?

**Comment by hmwildermuth** [comment]
@truell20 just the nycsl mongo db

**Comment by truell20** [comment]
We should be backing up storage too for games like Tron, where people give us their source.

**Comment by FlyingGraysons** [comment]
Will that not be in the db?

**Comment by truell20** [comment]
Updated last comment @FlyingGraysons

**Comment by hmwildermuth** [comment]
Ok. Send me the details of the folder names.

**Comment by truell20** [comment]
Backup the entire NYCSL2 folder with rsync. Don't save each archive. Overwrite each time.

**Comment by hmwildermuth** [comment]
ok

**Comment by hmwildermuth** [comment]
Done
