### ISSUE TITLE
Server should pull automatically

### ISSUE THREAD

**Issue by truell20** [HMProgrammingClub/NYCSL2#5]
It's annoying to have to ssh for every commit

**Comment by hmwildermuth** [comment]
@truell20 I can make it pull daily. Would that work?

**Comment by truell20** [comment]
nah super easy to make it pull automatically

**Comment by truell20** [comment]
just gotta use github webhooks, don't bother with cron

**Comment by truell20** [comment]
This probably isn't secure and is pretty unnecessary. I'm gonna close.
